In [1]:
import numpy as np;

In [2]:
print(np.arange(2,51,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [21]:
arr1=[] # empty list 1
arr2=[] # empty list 2

#take input for first list
for i in range(5):
    no = int(input("Enter Numbers for First List :"))
    arr1.append(no) # append to list 1
    
#take input for second list
i=0
for i in range(5):
    no = int(input("Enter Numbers for Second List :"))
    arr2.append(no) # append to list 2
    
arr1 = np.array(arr1) # lis1 convereted to numpy array
arr2 = np.array(arr2) # list2 converetd to numpy array

arr3 = np.concatenate((arr1,arr2)) # concatenate two numpy arrays
print("Concatenated Arrays :",arr3)
arr3 = np.sort((arr3)) # sorted the numpy array
print("Sorted Arrays :",arr3)

Enter Numbers for First List :5
Enter Numbers for First List :3
Enter Numbers for First List :6
Enter Numbers for First List :2
Enter Numbers for First List :8
Enter Numbers for Second List :12
Enter Numbers for Second List :24
Enter Numbers for Second List :30
Enter Numbers for Second List :4
Enter Numbers for Second List :7
Concatenated Arrays : [ 5  3  6  2  8 12 24 30  4  7]
Sorted Arrays : [ 2  3  4  5  6  7  8 12 24 30]


Q3 : Write a code snippet to find the dimensions of a ndarray and its size.

In [23]:
#Creating 2D array
arr = np.array([[1,2,3],[4,5,6],[9,8,7]]) 

print("Dimension of array is: ",arr.ndim) # Print dimension of array
print("Size of array is: ",arr.size) # Print size of array

Dimension of array is:  2
Size of array is:  9


Q4 : How to convert a 1D array into a 2D array? Demonstrate with the help of a c Hint: np.newaxis, np.expand_dims

In [84]:
#Define 1d array
arr=np.arange(4)
print("Array:", arr) # print 1D array

arr1 = arr.shape
print("Array Shape: ", arr1) # Print Shape

arr1 = arr.ndim
print("Array Dimension ", arr1) # Print Dimension

#using np.newaxis adding new axis along first dimension to make it 2D(row vector)

arr_r = arr[np.newaxis, :]
print("New Array:", arr_r)

arr1 = arr_r.shape
print("Array Shape changed using np.newaxis: ", arr1) # Print Shape

arr1 = arr_r.ndim
print("Array Dimemsion changed from 1D to 2D using np.newaxis: ",arr1)


#using np.expand_dims adding an axis at index position 0 to make it 2D

arr_r = np.expand_dims(arr,axis=0) 
print(arr_r)

arr1 = arr_r.shape
print("Array Shape changed using np.expand_dims: ", arr1) # Print Shape

arr1 = arr_r.ndim
print("Array Dimemsion changed from 1D to 2D using np.expand_dims: ",arr1)

Array: [0 1 2 3]
Array Shape:  (4,)
Array Dimension  1
New Array: [[0 1 2 3]]
Array Shape:  (1, 4)
Array Dimemsion changed from 1D to 2D using np.newaxis:  2
[[0 1 2 3]]
Array Shape:  (1, 4)
Array Dimemsion changed from 1D to 2D using np.expand_dims:  2


Q5:Consider two square numpy. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [95]:
# square numpy 1
arr1 = np.square([2,4,6,8]) 

# square numpy 2
arr2 = np.square([3,6,9,12]) 

print("Vertically Stacked: ",np.vstack((arr1,arr2))) # Vertically Stacked

print("Horizontally Stacked: ",np.hstack((arr1,arr2))) # Horizontally Stacked


Vertically Stacked:  [[  4  16  36  64]
 [  9  36  81 144]]
Horizontally Stacked:  [  4  16  36  64   9  36  81 144]


Q6: How to get unique items and counts of unique items?

In [100]:
# Original items
arr1=np.array([2,4,6,8,3,6,4,12])
print("Original Items: ",arr1)

unique_items,counts_items = np.unique(arr1, return_counts=True)

print("Count of unique values of the array:")
print(np.asarray((unique_items, counts_items)))

Original Items:  [ 2  4  6  8  3  6  4 12]
Count of unique values of the array:
[[ 2  3  4  6  8 12]
 [ 1  1  2  2  1  1]]
